name: deploy-non-prd
on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ENV_NAME: $( [ "$GITHUB_REF" == "refs/heads/master" ]
    steps:
      - name: Set env 
        run: echo "ENV_NAME=${{ env.ENV_NAME }} && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
      